### ISSUE TITLE
unable to click on the popup

### ISSUE THREAD

**Issue by killerbytes** [juliankrispel/use-text-selection#1] opened 2021-03-24 10:05 UTC
clicking on the popup will immediately close the popup

**Comment by juliankrispel** [comment] 2021-04-14 09:32
@killerbytes works for me, can you provide an example?

**Comment by kbariotis** [comment] 2021-05-02 17:21
@juliankrispel I think you can reproduce on the [example as well](https://juliankrispel.github.io/use-text-selection/). Clicking on the pop-up will close it automatically. This is a problem for when say you add a button to the pop up and when clicking on it you don't have the popup to close. I have the same issue with the `react-text-selection-popover` module as well.

Thanks :)

**Comment by juliankrispel** [comment] 2021-05-13 06:53
Ah I see what the misunderstanding here is, let me explain:
The `Share me` popover in the example is a div, therefore when clicking it the text selection is shifted to this element.
Making the element into a button or canceling the click event will keep the current text-selection intact. I've updated the example to use a button so it's less coonfusing.

Let me know if you have any questions, will close this issue for now.

**Closed as completed by juliankrispel** 2021-05-13 06:53 UTC
